name: ConsolePush
authors: [SOFe, PEMapModder]
version: 1.1.0
api:
- 2.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
main: PEMapModder\ConsolePush\ConsolePush
